[package]
name = "minibackup"
version = "0.1.0"
edition = "2021"

[dependencies]
ignore = "0.4.23"
passterm = "2.0.5"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
zip = "2.2.2"
